"""Test pricing consistency: micro-variants delegation + adaptor sync."""
from __future__ import annotations

import inspect

import pytest


class TestPricingDedup:
    """Micro-yuan pricing functions should delegate to yuan variants."""

    def test_calculate_cost_micro_delegates(self):
        """calculate_cost_micro should call calculate_cost internally."""
        from app.budget import pricing

        source = inspect.getsource(pricing.calculate_cost_micro)
        assert "calculate_cost(" in source, (
            "calculate_cost_micro should delegate to calculate_cost, "
            "not duplicate the formula"
        )

    def test_estimate_cost_micro_delegates(self):
        """estimate_cost_micro should call estimate_cost internally."""
        from app.budget import pricing

        source = inspect.getsource(pricing.estimate_cost_micro)
        assert "estimate_cost(" in source, (
            "estimate_cost_micro should delegate to estimate_cost, "
            "not duplicate the formula"
        )

    def test_values_consistent(self):
        """Micro variants should return yuan * 1_000_000 (rounded)."""
        from app.budget.pricing import calculate_cost, calculate_cost_micro

        yuan = calculate_cost("deepseek-v4-flash", 100, 50, 10)
        micro = calculate_cost_micro("deepseek-v4-flash", 100, 50, 10)
        expected_micro = max(1, int(round(yuan * 1_000_000)))
        assert micro == expected_micro, (
            f"calculate_cost_micro returned {micro}, "
            f"expected {expected_micro} (from calculate_cost)"
        )


class TestPricingSync:
    """Model pricing must be synced between adaptor pricing and budget pricing."""

    def test_all_adaptor_models_have_budget_pricing(self):
        """Every model in adaptor pricing files must have a matching entry
        in budget/pricing.py MODEL_PRICING_YUAN."""
        from app.relay.adaptors.deepseek.adaptor import DeepSeekAdaptor
        from app.relay.adaptors.glm.adaptor import GLMAdaptor
        from app.relay.adaptors.qwen.adaptor import QwenAdaptor
        from app.relay.adaptors.kimi.adaptor import KimiAdaptor
        from app.relay.adaptors.minimax.adaptor import MiniMaxAdaptor

        adaptor_models = set()
        for AdaptorCls in (DeepSeekAdaptor, GLMAdaptor, QwenAdaptor, KimiAdaptor, MiniMaxAdaptor):
            adaptor = AdaptorCls()
            adaptor_models.update(adaptor.get_supported_models().keys())

        from app.budget.pricing import MODEL_PRICING_YUAN
        budget_models = set(MODEL_PRICING_YUAN.keys())
        # Budget pricing has autogenerated lowercase aliases (e.g. "minimax-m3")
        # that duplicate the canonical name. Filter those out by keeping only the
        # entry that matches the adaptor's exact casing.
        budget_canonical = budget_models.copy()
        adaptor_lower = {m.lower() for m in adaptor_models}
        for bm in list(budget_canonical):
            if bm.lower() in adaptor_lower and bm not in adaptor_models:
                budget_canonical.discard(bm)

        missing = adaptor_models - budget_canonical
        assert not missing, (
            f"Models in adaptor pricing but missing from budget/pricing.py: {missing}"
        )

        extra = budget_canonical - adaptor_models
        assert not extra, (
            f"Models in budget/pricing.py but missing from adaptor pricing: {extra}"
        )
