"""add mcp_servers table

Revision ID: 11cc9084984c
Revises: 84e2074b399d
Create Date: 2026-06-23 13:02:43.188672
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11cc9084984c'
down_revision: Union[str, None] = '84e2074b399d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('protocol', sa.String(length=64), nullable=False),
    sa.Column('auth_type', sa.String(length=32), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('tool_whitelist', sa.Text(), nullable=True),
    sa.Column('tool_blacklist', sa.Text(), nullable=True),
    sa.Column('tool_pricing', sa.Text(), nullable=True),
    sa.Column('auto_sync_enabled', sa.Integer(), nullable=False),
    sa.Column('auto_sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.BigInteger(), nullable=False),
    sa.Column('last_sync_status', sa.String(length=32), nullable=True),
    sa.Column('last_test_at', sa.BigInteger(), nullable=False),
    sa.Column('last_test_status', sa.String(length=32), nullable=True),
    sa.Column('tool_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
