"""remove passkey totp aff security fields

Revision ID: 306a8eeb6f40
Revises: a7719b8
Create Date: 2026-06-29 10:11:05.366592
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306a8eeb6f40'
down_revision: Union[str, None] = 'a7719b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passkey_credentials_user_id'), table_name='passkey_credentials')
    op.drop_table('passkey_credentials')
    op.drop_index(op.f('ix_users_inviter_id'), table_name='users')
    op.drop_column('users', 'inviter_id')
    op.drop_column('users', 'aff_code')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'pending_totp_secret')
    op.drop_column('users', 'totp_secret')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'pending_totp_expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_totp_expires_at', sa.BIGINT(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.BIGINT(), nullable=True))
    op.add_column('users', sa.Column('totp_secret', sa.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('pending_totp_secret', sa.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True))
    op.add_column('users', sa.Column('aff_code', sa.VARCHAR(length=32), nullable=True))
    op.add_column('users', sa.Column('inviter_id', sa.INTEGER(), nullable=True))
    op.create_index(op.f('ix_users_inviter_id'), 'users', ['inviter_id'], unique=False)
    op.create_table('passkey_credentials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('credential_id', sa.VARCHAR(length=512), nullable=False),
    sa.Column('public_key', sa.TEXT(), nullable=False),
    sa.Column('sign_count', sa.INTEGER(), nullable=False),
    sa.Column('credential_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('transports', sa.VARCHAR(length=256), nullable=False),
    sa.Column('created_at', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    op.create_index(op.f('ix_passkey_credentials_user_id'), 'passkey_credentials', ['user_id'], unique=False)
    # ### end Alembic commands ###
