"""add redemption_codes table

Revision ID: 84e2074b399d
Revises: 254b7e6cbcbb
Create Date: 2026-06-23 07:34:35.467115
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e2074b399d'
down_revision: Union[str, None] = '254b7e6cbcbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redemption_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('quota', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_time', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redemption_codes_code'), 'redemption_codes', ['code'], unique=True)
    op.create_index(op.f('ix_redemption_codes_used_by'), 'redemption_codes', ['used_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redemption_codes_used_by'), table_name='redemption_codes')
    op.drop_index(op.f('ix_redemption_codes_code'), table_name='redemption_codes')
    op.drop_table('redemption_codes')
    # ### end Alembic commands ###
