"""add redemption_codes table

Revision ID: 84e2074b399d
Revises: 254b7e6cbcbb
Create Date: 2026-06-23 07:34:35.467115
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e2074b399d'
down_revision: Union[str, None] = '254b7e6cbcbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('group', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.BigInteger(), nullable=False),
    sa.Column('suspend_until', sa.Time(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('group', 'model', 'channel_id')
    )
    op.create_index(op.f('ix_abilities_priority'), 'abilities', ['priority'], unique=False)
    op.create_table('budget_reset_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('total_consumed', sa.Float(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('reset_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_reset_logs_user_id'), 'budget_reset_logs', ['user_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monthly_budget', sa.Float(), nullable=False),
    sa.Column('consumed', sa.Float(), nullable=False),
    sa.Column('frozen', sa.Float(), nullable=False),
    sa.Column('budget_period', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=True)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('test_time', sa.BigInteger(), nullable=False),
    sa.Column('response_time', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('other', sa.Text(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('balance_updated_time', sa.BigInteger(), nullable=False),
    sa.Column('models', sa.Text(), nullable=True),
    sa.Column('model_configs', sa.Text(), nullable=True),
    sa.Column('group', sa.String(length=64), nullable=False),
    sa.Column('used_quota', sa.BigInteger(), nullable=False),
    sa.Column('model_mapping', sa.Text(), nullable=True),
    sa.Column('priority', sa.BigInteger(), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('testing_model', sa.String(length=255), nullable=True),
    sa.Column('inference_profile_arn_map', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_name'), 'channels', ['name'], unique=False)
    op.create_table('cost_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_hit_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('agent_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_records_request_id'), 'cost_records', ['request_id'], unique=True)
    op.create_index(op.f('ix_cost_records_user_id'), 'cost_records', ['user_id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('token_name', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('quota', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('elapsed_time', sa.BigInteger(), nullable=False),
    sa.Column('is_stream', sa.Boolean(), nullable=False),
    sa.Column('system_prompt_reset', sa.Boolean(), nullable=False),
    sa.Column('cached_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_completion_tokens', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_channel_id'), 'logs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_logs_created_at'), 'logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_logs_model_name'), 'logs', ['model_name'], unique=False)
    op.create_index(op.f('ix_logs_request_id'), 'logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_logs_token_name'), 'logs', ['token_name'], unique=False)
    op.create_index(op.f('ix_logs_type'), 'logs', ['type'], unique=False)
    op.create_index(op.f('ix_logs_user_id'), 'logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_logs_username'), 'logs', ['username'], unique=False)
    op.create_table('options',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('redemption_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('quota', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_time', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redemption_codes_code'), 'redemption_codes', ['code'], unique=True)
    op.create_index(op.f('ix_redemption_codes_used_by'), 'redemption_codes', ['used_by'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('accessed_time', sa.BigInteger(), nullable=False),
    sa.Column('expired_time', sa.BigInteger(), nullable=False),
    sa.Column('remain_quota', sa.BigInteger(), nullable=False),
    sa.Column('unlimited_quota', sa.Boolean(), nullable=False),
    sa.Column('used_quota', sa.BigInteger(), nullable=False),
    sa.Column('models', sa.Text(), nullable=True),
    sa.Column('subnet', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_key'), 'tokens', ['key'], unique=True)
    op.create_index(op.f('ix_tokens_name'), 'tokens', ['name'], unique=False)
    op.create_index(op.f('ix_tokens_user_id'), 'tokens', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('github_id', sa.String(length=64), nullable=True),
    sa.Column('wechat_id', sa.String(length=64), nullable=True),
    sa.Column('lark_id', sa.String(length=64), nullable=True),
    sa.Column('oidc_id', sa.String(length=64), nullable=True),
    sa.Column('access_token', sa.String(length=64), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('quota', sa.BigInteger(), nullable=False),
    sa.Column('used_quota', sa.BigInteger(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=32), nullable=False),
    sa.Column('aff_code', sa.String(length=32), nullable=True),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('mcp_tool_blacklist', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('aff_code')
    )
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=False)
    op.create_index(op.f('ix_users_inviter_id'), 'users', ['inviter_id'], unique=False)
    op.create_index(op.f('ix_users_lark_id'), 'users', ['lark_id'], unique=False)
    op.create_index(op.f('ix_users_oidc_id'), 'users', ['oidc_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_wechat_id'), 'users', ['wechat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_wechat_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_oidc_id'), table_name='users')
    op.drop_index(op.f('ix_users_lark_id'), table_name='users')
    op.drop_index(op.f('ix_users_inviter_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tokens_user_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_name'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_key'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_redemption_codes_used_by'), table_name='redemption_codes')
    op.drop_index(op.f('ix_redemption_codes_code'), table_name='redemption_codes')
    op.drop_table('redemption_codes')
    op.drop_table('options')
    op.drop_index(op.f('ix_logs_username'), table_name='logs')
    op.drop_index(op.f('ix_logs_user_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_type'), table_name='logs')
    op.drop_index(op.f('ix_logs_token_name'), table_name='logs')
    op.drop_index(op.f('ix_logs_request_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_model_name'), table_name='logs')
    op.drop_index(op.f('ix_logs_created_at'), table_name='logs')
    op.drop_index(op.f('ix_logs_channel_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_cost_records_user_id'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_request_id'), table_name='cost_records')
    op.drop_table('cost_records')
    op.drop_index(op.f('ix_channels_name'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_budget_reset_logs_user_id'), table_name='budget_reset_logs')
    op.drop_table('budget_reset_logs')
    op.drop_index(op.f('ix_abilities_priority'), table_name='abilities')
    op.drop_table('abilities')
    # ### end Alembic commands ###
